// GENERATED by scripts/build-validator.mjs from schema/messages.schema.json.
// Do not edit. Run `npm run build:validator`; CI fails on a diff.

/** One Ajv error. `message` is optional in Ajv's own types, so it is here too. */
export interface ValidationError {
  instancePath: string;
  schemaPath: string;
  keyword: string;
  params: Record<string, unknown>;
  message?: string;
}

export interface ValidateFunction {
  (data: unknown): boolean;
  /** Populated on a failed call, reset on the next one. */
  errors?: ValidationError[] | null;
}

declare const validate: ValidateFunction;
export default validate;
export { validate };
